CREATE TABLE USER_INFO(
    USER_ID VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    STATUS VARCHAR(5) NOT NULL,
    USER_TYPE VARCHAR(20) NOT NULL,
)